### preliminary experiment: baseline

In [1]:
import os
import pandas as pd
import numpy as np
import seaborn as sns
%matplotlib inline

In [108]:
# load datasets
dataset_feature = pd.read_pickle('../datasets/dataset_featurecode.dataset')
print(dataset_feature)

       gene uniprotac variant          drug  \
0    MAP2K1    Q02750   P124S   Selumetinib   
1    MAP2K1    Q02750    Q56P   Selumetinib   
2    PDGFRA    P16234   D842V      Imatinib   
3      ARAF    P10398   S214C     Sorafenib   
4      JAK2    O60674   V617F    Fedratinib   
..      ...       ...     ...           ...   
750    NQO1    P15559   P187S      warfarin   
751     MTR    Q99707   D919G  methotrexate   
752   ADH1C    P00326   I350V    naltrexone   
753   ADH1B    P00325   R370C    naltrexone   
754   MTHFR    P42898   A222V  methotrexate   

                                                 smile  \
0    CN1C=NC2=C1C=C(C(=C2F)NC3=C(C=C(C=C3)Br)Cl)C(=...   
1    CN1C=NC2=C1C=C(C(=C2F)NC3=C(C=C(C=C3)Br)Cl)C(=...   
2    CC1=C(C=C(C=C1)NC(=O)C2=CC=C(C=C2)CN3CCN(CC3)C...   
3    CNC(=O)C1=NC=CC(=C1)OC2=CC=C(C=C2)NC(=O)NC3=CC...   
4    CC1=CN=C(N=C1NC2=CC(=CC=C2)S(=O)(=O)NC(C)(C)C)...   
..                                                 ...   
750       CC(=O)CC(C1=CC=CC=C

In [109]:
from sklearn.utils import shuffle
shuffled_dataset = shuffle(dataset_feature)
print(shuffled_dataset)

       gene uniprotac variant         drug  \
73     BRAF    P15056   L597R  Vemurafenib   
2    PDGFRA    P16234   D842V     Imatinib   
78      ALK    Q9UM73  L1152R   Crizotinib   
336    EGFR    P00533   R776C    Erlotinib   
131     ALK    Q9UM73  G1269A   Brigatinib   
..      ...       ...     ...          ...   
232    ABL1    P00519   Q252H     Imatinib   
452    CFTR    P13569    P67L    ivacaftor   
310    EGFR    P00533   L858R   Crizotinib   
720    CFTR    P13569    E92K    ivacaftor   
218     KIT    P10721   D816V     Imatinib   

                                                 smile  \
73   CCCS(=O)(=O)NC1=C(C(=C(C=C1)F)C(=O)C2=CNC3=C2C...   
2    CC1=C(C=C(C=C1)NC(=O)C2=CC=C(C=C2)CN3CCN(CC3)C...   
78   C[C@H](C1=C(C=CC(=C1Cl)F)Cl)OC2=C(N=CC(=C2)C3=...   
336  COCCOC1=C(C=C2C(=C1)C(=NC=N2)NC3=CC=CC(=C3)C#C...   
131  CN1CCN(CC1)C2CCN(CC2)C3=CC(=C(C=C3)NC4=NC=C(C(...   
..                                                 ...   
232  CC1=C(C=C(C=C1)NC(=O)C2=CC=C(C=C2)CN

In [91]:
shuffled_dataset['label'].value_counts()

1    509
0    196
Name: label, dtype: int64

In [46]:
feature_cols = pd.DataFrame(shuffled_dataset, columns=['onehot_before', 'onehot_after', 'hhm_before', 'hhm_after', 'rasa', 'ss',
                                                        'smile_num','cactvs_fingerprint', 'molecular_weight'])

In [110]:
shuffled_dataset = shuffled_dataset.reset_index(drop=True)
#print(shuffled_dataset)
shuffled_dataset['onehot_before'][5]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]])

In [117]:
# flatten features
label = shuffled_dataset['label'].values
feature = np.zeros(shape=(shuffled_dataset.shape[0],6271))
for i in range(shuffled_dataset.shape[0]):
    sample_list = []
    onehot_before = shuffled_dataset['onehot_before'][i]
    for item in np.nditer(onehot_before):
        sample_list.append(int(item))
    onehot_after = shuffled_dataset['onehot_after'][i]
    for item in np.nditer(onehot_after):
        sample_list.append(int(item))
    hhm_before = shuffled_dataset['hhm_before'][i]
    for item in np.nditer(hhm_before):
        sample_list.append(int(item))
    hhm_after = shuffled_dataset['hhm_after'][i]
    for item in np.nditer(hhm_after):
        sample_list.append(int(item))
    rasa = shuffled_dataset['rasa'][i]
    for item in rasa:
        sample_list.append(item)
    ss = shuffled_dataset['ss'][i]
    for item in np.nditer(ss):
        sample_list.append(int(item))
    smile_num = shuffled_dataset['smile_num'][i]
    for item in smile_num:
        sample_list.append(int(item))
    cactvs_fingerprint = shuffled_dataset['cactvs_fingerprint'][i]
    for item in cactvs_fingerprint:
        sample_list.append(int(item))
    molecular_weight = shuffled_dataset['molecular_weight'][i]
    sample_list.append(molecular_weight)
    #print(sample_list)
    for j in range(len(sample_list)):
        feature[i, j] = sample_list[j]
print(feature)

[[  0.    0.    0.  ...   0.    0.  489.9]
 [  0.    0.    0.  ...   0.    0.  493.6]
 [  0.    0.    0.  ...   0.    0.  450.3]
 ...
 [  0.    0.    0.  ...   0.    0.  450.3]
 [  0.    0.    0.  ...   0.    0.  392.5]
 [  0.    0.    0.  ...   0.    0.  493.6]]


#### Model 1: Decision tree

In [47]:
from sklearn.tree import DecisionTreeClassifier
X = feature_cols.values
Y = 
clf = DecisionTreeClassifier()
clf.fit(X, Y)

ValueError: setting an array element with a sequence.